ydlidar_ros2_param:
  ros__parameters:
    port: /dev/ttyUSB0
    frame_id: laser_frame
    ignore_array: ""
    baudrate: 230400
    lidar_type: 1
    device_type: 0
    sample_rate: 5
    abnormal_check_count: 4
    resolution_fixed: true
    auto_reconnect: true
    reversion: true
    inverted: true
    isSingleChannel: false
    intensity: true
    support_motor_dtr: false
    invalid_range_is_inf: false
    point_cloud_preservative: false
    angle_min: -180
    angle_max: 180
    range_min: 0.1
    range_max: 16.0
    frequency: 10.0

